//default action
export const FETCH_PRODUCTS_BEGIN = 'FETCH_PRODUCTS_BEGIN';
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS';
export const FETCH_SINGLE_PRODUCT = 'FETCH_SINGLE_PRODUCT';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADD_TO_WISHLIST = 'ADD_TO_WISHLIST';
export const REMOVE_FROM_WISHLIST = 'REMOVE_FROM_WISHLIST';
export const INCREMENT_QUANTITY = 'INCREMENT_QUANTITY';
export const DECREMENT_QUANTITY = 'DECREMENT_QUANTITY';
export const ADD_TO_COMPARE = 'ADD_TO_COMPARE';
export const REMOVE_FROM_COMPARE_LIST = 'REMOVE_FROM_COMPARE_LIST';
export const ADD_SUBS_PRODUCT_TO_CART = 'ADD_SUBS_PRODUCT_TO_CART';
export const REMOVE_FROM_SUB_CART = 'REMOVE_FROM_SUB_CART';
export const INCREMENT_SUB_QUANTITY = 'INCREMENT_SUB_QUANTITY';
export const DECREMENT_SUB_QUANTITY = 'DECREMENT_SUB_QUANTITY';
export const EDIT_SUB_PRODUCT = 'EDIT_SUB_PRODUCT';